name: Build Ascend APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: HTML to APK
        uses: kimhuilim/web-to-app-action@Alpha3
        with:
          build-folder-path: '.'
          app-name: 'Ascend'
          app-id-apk: 'com.you.ascend'
          output-folder-path: 'apk-output'
